name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: Stephen-Agyemang
          outputs: |
            dist/snake-dark.gif?palette=github-dark
            dist/dots-dark.svg?palette=github-dark&color_dots=#00F2FE,#00D9F5,#00BFE8,#00A6DC,#008DCF
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
